### ISSUE TITLE
Add test for try-with-resources statement

### ISSUE THREAD

**Issue by dodie** [dodie/scott#46]
Enhance the test suite to verify that variables in tests containing `try-with-resource` statements are correctly recorded. Similar tests can be found in the [junit4-tests](https://github.com/dodie/scott/tree/master/scott-tests/junit4-tests) project.

Also, add a failing test to the [showcase project](https://github.com/dodie/scott/tree/master/scott-examples/junit4), to make sure that the rendered failure message looks pretty.

Note: please make sure to visit the [contribution](https://github.com/dodie/scott/tree/master/CONTRIBUTING.md) and [development guide](https://github.com/dodie/scott/tree/master/docs/development-guide.md) for some important notes on how to build and debug Scott.

**Comment by kevinkraus** [comment]
Hi - may I give this a try?

**Comment by dodie** [comment]
Hi @kevinkraus, sure!

**Comment by kevinkraus** [comment]
Hi @dodie - I wrote a test and I'm getting an `EmptyStackException` while running it. All the other tests work, and when I refactored this test without try-with-resources, it worked ok. Is there anything I'm doing wrong here? Any help would be appreciated.

```
    @Test
    public void try_with_resources() {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream();
             PrintStream printStream = new PrintStream(out)) {

            printStream.append("Hello World");

            assertThat(TestHelper.getLastRecordedStateForVariable("out"), equalTo(out.toString()));
        } catch (Exception e) {

        }
    }
```

Leads to:

```
Scott: test instrumentation failed for hu/advancedweb/scott/TryWithResourcesRecordingTest!
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at hu.advancedweb.scott.instrumentation.transformation.ScopeExtractorTestMethodVisitor.calculateScope(ScopeExtractorTestMethodVisitor.java:153)
	at hu.advancedweb.scott.instrumentation.transformation.ScopeExtractorTestMethodVisitor.visitEnd(ScopeExtractorTestMethodVisitor.java:111)
	at hu.advancedweb.shaded.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1130)
	at hu.advancedweb.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at hu.advancedweb.shaded.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at hu.advancedweb.scott.instrumentation.transformation.TestClassTransformer.transform(TestClassTransformer.java:52)
	at hu.advancedweb.scott.instrumentation.transformation.TestClassTransformer.transform(TestClassTransformer.java:32)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:131)
	at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:96)
	at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:311)
	at org.apache.maven.surefire.junit4.JUnit4Provider.setTestsToRun(JUnit4Provider.java:191)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:134)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

```
Expected: "Hello World"
     but: was null
	at hu.advancedweb.scott.TryWithResourcesRecordingTest.try_with_resources(TryWithResourcesRecordingTest.java:20)
```

**Comment by dodie** [comment]
Your test is fine - you found a bug in Scott. I did not have time to investigate it yet, but from the exception you got it seems that the line [number calculation](ScopeExtractorTestMethodVisitor.java#L123) does not support the try-with-resources.

It would be awesome if you have time to give this bug a shot, however it might take some time to figure out the problem as it's inside the bowels of Scott. 

If you don't have time for it, please still open a Pull Request with the breaking test, as it provides an example to reproduce the bug.

**Comment by kevinkraus** [comment]
Sure, I'll give it a shot.
