### ISSUE TITLE
ArrayIndexOutOfBoundsException on instumentation

### ISSUE THREAD

**Issue by dodie** [dodie/scott#57]
In some environments the instrumentation fails with the following error:
```
java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:422)
        at java.util.ArrayList.get(ArrayList.java:435)
        at hu.advancedweb.scott.instrumentation.transformation.ScopeExtractorTestMethodVisitor.visitVarInsn(ScopeExtractorTestMethodVisitor.java:88)
```

Logging the events reveals that a single `visitVarInsn` happens before the first `visitLabel`, and this causes the error.

**Comment by dodie** [comment]
Because otherwise all visit events happen normally, it seems pretty safe to simply ignore this first `visitvarIns` in case it happens.
